"""
Expanded comprehensive Italian stopwords.
"""

STOP_WORDS = {
    # === ARTICLES & PREPOSITIONS ===
    'il', 'lo', 'la', 'i', 'gli', 'le', 'un', 'uno', 'una',
    'di', 'a', 'da', 'in', 'con', 'su', 'per', 'tra', 'fra',
    'del', 'della', 'dei', 'degli', 'delle', 
    'al', 'alla', 'ai', 'agli', 'alle',
    'dal', 'dalla', 'dai', 'dagli', 'dalle', 
    'nel', 'nella', 'nei', 'negli', 'nelle',
    'sul', 'sulla', 'sui', 'sugli', 'sulle',
    'col', 'coi', 'pel', 'pei',
    # Truncated forms commonly found after tokenization (e.g. "dell'Italia" -> "dell")
    'dell', 'dall', 'nell', 'sull', 'all', 'gl', 'un', 'c', 'l', 'd', 'v', 'n', 's',
    
    # === PRONOUNS ===
    'io', 'tu', 'egli', 'ella', 'esso', 'essa', 'noi', 'voi', 'essi', 'esse',
    'lui', 'lei', 'loro', 'me', 'te', 'sé',
    'mi', 'ti', 'si', 'ci', 'vi', 'ne', 'lo', 'la', 'li', 'le',
    'mio', 'mia', 'miei', 'mie', 'tuo', 'tua', 'tuoi', 'tue',
    'suo', 'sua', 'suoi', 'sue', 'nostro', 'nostra', 'nostri', 'nostre',
    'vostro', 'vostra', 'vostri', 'vostre',
    'questo', 'questa', 'questi', 'queste', 'quello', 'quella', 'quelli', 'quelle',
    'ciò', 'costui', 'costei', 'costoro', 'colui', 'colei', 'coloro',
    'chi', 'che', 'cui', 'quale', 'quali',
    
    # === INTERROGATIVES ===
    'cosa', 'come', 'dove', 'quando', 'perché', 'quanto', 'quanta', 'quanti', 'quante',
    
    # === INDEFINITES ===
    'ogni', 'tutto', 'tutti', 'tutta', 'tutte', 
    'altro', 'altri', 'altra', 'altre', 'altrui',
    'stesso', 'stessa', 'stessi', 'stesse',
    'proprio', 'propria', 'propri', 'proprie',
    'qualche', 'qualcuno', 'qualcuna', 'qualcosa', 
    'chiunque', 'checché', 'chicchessia',
    'nessuno', 'nessuna', 'niente', 'nulla',
    'alcuno', 'alcuna', 'alcuni', 'alcune',
    'ciascuno', 'ciascuna', 'tale', 'tali',
    'certo', 'certa', 'certi', 'certe',
    'vario', 'varia', 'vari', 'varie',
    'troppo', 'troppa', 'troppi', 'troppe',
    'poco', 'poca', 'pochi', 'poche',
    'molto', 'molta', 'molti', 'molte',
    'tanto', 'tanta', 'tanti', 'tante',
    'parecchio', 'parecchia', 'parecchi', 'parecchie',
    
    # === VERBS: ESSERE ===
    'essere', 'sono', 'sei', 'è', 'siamo', 'siete',
    'ero', 'eri', 'era', 'eravamo', 'eravate', 'erano',
    'fui', 'fosti', 'fu', 'fummo', 'foste', 'furono',
    'sarò', 'sarai', 'sarà', 'saremo', 'sarete', 'saranno',
    'sia', 'siate', 'siano', 'fossi', 'fosse', 'fossimo', 'fossero',
    'sarei', 'saresti', 'sarebbe', 'saremmo', 'sareste', 'sarebbero',
    'stato', 'stata', 'stati', 'state', 'essendo',
    
    # === VERBS: AVERE ===
    'avere', 'ho', 'hai', 'ha', 'abbiamo', 'avete', 'hanno',
    'avevo', 'avevi', 'aveva', 'avevamo', 'avevate', 'avevano',
    'ebbi', 'avesti', 'ebbe', 'avemmo', 'aveste', 'ebbero',
    'avrò', 'avrai', 'avrà', 'avremo', 'avrete', 'avranno',
    'abbia', 'abbiate', 'abbiano', 'avessi', 'avesse', 'avessimo', 'avessero',
    'avrei', 'avresti', 'avrebbe', 'avremmo', 'avreste', 'avrebbero',
    'avuto', 'avuta', 'avuti', 'avute', 'avendo',
    
    # === COMMON VERBS ===
    'fare', 'fatto', 'fatta', 'fatti', 'fatte', 'fa', 'fanno', 'facendo', 'farà',
    'dire', 'detto', 'detta', 'detti', 'dette', 'dice', 'dicendo', 'dirà',
    'andare', 'andato', 'va', 'vanno', 'andando', 'andrà',
    'venire', 'venuto', 'viene', 'vengono', 'venendo', 'verrà',
    'potere', 'può', 'possono', 'potuto', 'potrà', 'potrebbe',
    'volere', 'vuole', 'vogliono', 'voluto', 'vorrà', 'vorrebbe',
    'dovere', 'deve', 'devono', 'dovuto', 'dovrà', 'dovrebbe',
    'stare', 'sta', 'stanno', 'stando', 'starà',
    'dare', 'dà', 'danno', 'dato', 'data', 'dati', 'date',
    'sapere', 'sa', 'sanno', 'saputo', 'saprà',
    'vedere', 'vede', 'vedono', 'visto', 'vista', 'vedrà',
    'prendere', 'prende', 'preso', 'presa', 'prenderà',
    'mettere', 'mette', 'messo', 'messa', 'metterà',
    'trovare', 'trova', 'trovato', 'troverà',
    'sentire', 'sente', 'sentito', 'sentirà',
    'parlare', 'parla', 'parlato', 'parlerà',
    'pensare', 'pensa', 'pensato', 'penserà',
    'credere', 'crede', 'creduto', 'crederà',
    'chiamare', 'chiama', 'chiamato', 'chiamerà',
    'portare', 'porta', 'portato', 'porterà',
    'passare', 'passa', 'passato', 'passerà',
    'restare', 'resta', 'restato', 'resterà',
    'lasciare', 'lascia', 'lasciato', 'lascerà',
    'tenere', 'tiene', 'tenuto', 'terrà',
    'seguire', 'segue', 'seguito', 'seguirà',
    'rendere', 'rende', 'reso', 'renderà',
    
    # === ADVERBS ===
    'non', 'più', 'già', 'ancora', 'sempre', 'mai', 'ora', 'adesso', 
    'oggi', 'ieri', 'domani', 'qui', 'qua', 'là', 'lì',
    'molto', 'poco', 'tanto', 'troppo', 'abbastanza', 'quasi', 'appena',
    'bene', 'male', 'meglio', 'peggio', 'così', 'come',
    'forse', 'probabilmente', 'certamente', 'sicuramente',
    'veramente', 'davvero', 'proprio', 'solo', 'soltanto', 'solamente',
    'insieme', 'separatamente', 'diversamente', 'altrimenti',
    'prima', 'dopo', 'poi', 'quindi', 'dunque', 'pertanto', 'perciò',
    'inoltre', 'infine', 'finalmente', 'soprattutto', 'specialmente',
    'particolarmente', 'principalmente', 'essenzialmente', 'naturalmente',
    'ovviamente', 'evidentemente', 'chiaramente', 'effettivamente',
    
    # === CONJUNCTIONS ===
    'e', 'ed', 'o', 'od', 'ma', 'però', 'tuttavia', 'eppure', 'anzi',
    'né', 'neanche', 'nemmeno', 'neppure',
    'che', 'se', 'perché', 'poiché', 'giacché', 'siccome', 'dato',
    'quando', 'mentre', 'finché', 'affinché', 'purché',
    'sebbene', 'benché', 'nonostante', 'malgrado',
    'come', 'quanto', 'qualora', 'laddove',
    'cioè', 'ossia', 'ovvero', 'oppure', 'infatti', 'invero',
    
    # === NUMBERS ===
    'uno', 'due', 'tre', 'quattro', 'cinque', 'sei', 'sette', 'otto', 'nove', 'dieci',
    'primo', 'secondo', 'terzo', 'quarto', 'quinto',
    'prima', 'seconda', 'terza', 'quarta', 'quinta',
    
    # === PARLIAMENTARY/FORMAL TERMS (non-distinctive) ===
    'presidente', 'signor', 'signora', 'signori', 'signore',
    'onorevole', 'onorevoli', 'colleghi', 'colleghe', 'collega',
    'ministro', 'ministri', 'sottosegretario', 'viceministro',
    'senatore', 'senatori', 'senatrice', 'senatrici',
    'deputato', 'deputati', 'deputata', 'deputate',
    'relatore', 'relatrice', 'relatori',
    'governo', 'parlamento', 'camera', 'senato', 'aula',
    'commissione', 'commissioni', 'comitato', 'comitati',
    'seduta', 'sedute', 'sessione', 'sessioni',
    'votazione', 'votazioni', 'voto', 'voti',
    'emendamento', 'emendamenti', 'subemendamento',
    'articolo', 'articoli', 'comma', 'commi', 'lettera', 'lettere',
    'legge', 'leggi', 'decreto', 'decreti', 'norma', 'norme', 'normativa',
    'disegno', 'proposta', 'proposte', 'mozione', 'mozioni',
    'ordine', 'giorno', 'punto', 'punti',
    'discussione', 'discussioni', 'dibattito', 'dibattiti',
    'intervento', 'interventi', 'parola', 'parole',
    'documento', 'documenti', 'testo', 'testi', 'allegato', 'allegati',
    'provvedimento', 'provvedimenti', 'misura', 'misure',
    'modifica', 'modifiche', 'modifica', 'integrazione', 'integrazioni',
    'attuazione', 'applicazione', 'disposizione', 'disposizioni',
    'termine', 'termini', 'proroga', 'proroghe',
    'approvazione', 'approvato', 'approvata', 'approvati', 'approvate',
    'rinvio', 'rinviato', 'rinviata',
    'favor', 'favore', 'favorevole', 'favorevoli',
    'contrario', 'contrari', 'contraria', 'contrarie',
    'astenuto', 'astenuti', 'astensione', 'astensioni',
    
    # === GENERIC TERMS ===
    'anno', 'anni', 'mese', 'mesi', 'giorno', 'giorni', 'settimana', 'settimane',
    'volta', 'volte', 'modo', 'modi', 'caso', 'casi', 'tipo', 'tipi',
    'parte', 'parti', 'punto', 'punti', 'fatto', 'fatti',
    'cosa', 'cose', 'questione', 'questioni', 'problema', 'problemi',
    'esempio', 'esempi', 'senso', 'sensi', 'base', 'basi',
    'tema', 'temi', 'argomento', 'argomenti', 'materia', 'materie',
    'rispetto', 'riguardo', 'confronto', 'merito',
    'paese', 'paesi', 'stato', 'stati', 'nazione', 'nazioni',
    'italia', 'italiano', 'italiana', 'italiani', 'italiane',
    'europa', 'europeo', 'europea', 'europei', 'europee', 'fratelli', 'fratello', 'fratelle', 'fratelli',
    'opposizioni',

    # === FORMAL/COURTESY EXPRESSIONS ===
    'ringrazio', 'ringraziare', 'ringraziamo', 'ringraziamento', 'ringraziamenti',
    'grazie', 'prego', 'cortesia', 'cortese', 'cortesemente',
    'odierna', 'odierno', 'odierni', 'odierne',
    'regolamento', 'regolamenti', 'regolamentare', 'regolamentari',
    'signori', 'signore', 'gentili', 'gentile', 'egregio', 'egregia',
    'illustre', 'illustri', 'preg.mo', 'spett.le',
    
    # === ADDITIONAL COMPREHENSIVE STOPWORDS ===
    'capigruppo', 'capogruppo',
    'abbastanza', 'accidenti', 'ahime', 'ahimè', 'allora', 'altrove',
    'ansa', 'anticipo', 'assai', 'attesa', 'attraverso', 'avanti',
    'aver', 'averlo', 'avente',
    'basta', 'ben', 'benissimo', 'brava', 'bravo', 'buono',
    'cento', 'chicchessia', 'cima', 'citta', 'città', 'cio',
    'codesta', 'codesti', 'codesto', 'cogli', 'coll', 'cominci',
    'comprare', 'comunque', 'concernente', 'conclusione', 
    'consecutivi', 'consecutivo', 'consiglio', 'contro',
    'cos', 'dappertutto', 'davanti', 'dentro', 'dirimpetto',
    'diventa', 'diventare', 'diventato', 'doppio', 'dov', 'dovra',
    'dovunque', 'ecc', 'ecco', 'entrambi', 'eppure', 'esser',
    'ex', 'faccia', 'facciamo', 'facciano', 'facciate', 'faccio',
    'facemmo', 'facesse', 'facessero', 'facessi', 'facessimo',
    'faceste', 'facesti', 'faceva', 'facevamo', 'facevano',
    'facevate', 'facevi', 'facevo', 'fai', 'farai', 'faranno',
    'farebbe', 'farebbero', 'farei', 'faremmo', 'faremo',
    'fareste', 'faresti', 'farete', 'farò', 'fece', 'fecero', 'feci',
    'fin', 'finche', 'fine', 'fino', 'forza', 'fra', 'frattempo',
    'futuro', 'generale', 'gente', 'gia', 'giacche', 'giu',
    'grande', 'gruppo', 'haha', 'ie', 'improvviso', 'inc',
    'indietro', 'infatti', 'insieme', 'intanto', 'intorno', 'invece',
    'lasciato', 'lato', 'lontano', 'lungo', 'luogo', 'là',
    'macche', 'magari', 'maggior', 'medesimo', 'mediante',
    'mila', 'miliardi', 'milioni', 'minimi', 'momento', 'mondo',
    'negl', 'nondimeno', 'nonsia', 'novanta', 'nuovi', 'nuovo',
    'ore', 'osi', 'ottanta', 'partendo', 'peccato', 'percio',
    'perfino', 'pero', 'persino', 'persone', 'piedi', 'pieno',
    'piglia', 'piu', 'piuttosto', 'po', 'pochissimo', 'poiche',
    'possa', 'possedere', 'posteriore', 'posto', 'preferibilmente',
    'presa', 'press', 'primo', 'promesso', 'puo', 'pure', 'purtroppo',
    'qua', 'quantunque', 'quel', 'quest', 'quinto',
    'realmente', 'recente', 'recentemente', 'registrazione',
    'relativo', 'riecco', 'salvo', 'sara', 'scola', 'scopo', 'scorso',
    'seguente', 'sembra', 'sembrare', 'sembrato', 'sembrava', 'sembri',
    'senza', 'sig', 'solito', 'spesso', 'stai', 'starai', 'staranno',
    'starebbe', 'starebbero', 'starei', 'staremmo', 'staremo',
    'stareste', 'staresti', 'starete', 'starò', 'stava', 'stavamo',
    'stavano', 'stavate', 'stavi', 'stavo', 'stemmo', 'stette',
    'stettero', 'stetti', 'stia', 'stiamo', 'stiano', 'stiate', 'sto',
    'subito', 'successivamente', 'successivo', 'sugl', 'talvolta',
    'terzo', 'th', 'titolo', 'tranne', 'trenta', 'triplo', 'uguali',
    'ulteriore', 'ultimo', 'uomo', 'vai', 'vale', 'verso', 'vicino',
    'vita',
}
