"""
Regenerate docs/JSON_SCHEMA.md from the payload that was actually written.

The previous schema doc was maintained by hand and drifted: it documented
`qualitative` and `speaker_stats` sections and an `analytics.available_periods`
key, none of which the pipeline emitted. Since it is the contract the frontend
is written against, it is now derived from the real artifacts.

    python -m backend.tools.dump_schema
"""

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DATA_DIR = PROJECT_ROOT / 'frontend' / 'public' / 'data'
DOC_PATH = PROJECT_ROOT / 'docs' / 'JSON_SCHEMA.md'

MAX_SAMPLE_CHARS = 60


def describe(value, depth=0, max_depth=2) -> str:
    """One-line type description of a JSON value."""
    if isinstance(value, dict):
        if depth >= max_depth or not value:
            return f"object ({len(value)} keys)"
        keys = list(value)[:6]
        suffix = ', …' if len(value) > 6 else ''
        return "object {" + ", ".join(keys) + suffix + "}"
    if isinstance(value, list):
        if not value:
            return "array (empty)"
        return f"array[{len(value)}] of {describe(value[0], depth + 1, max_depth)}"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if value is None:
        return "null"
    text = str(value)
    if len(text) > MAX_SAMPLE_CHARS:
        text = text[:MAX_SAMPLE_CHARS] + '…'
    return f'string ("{text}")'


def field_table(sample: dict, title: str) -> list[str]:
    lines = [f"### {title}", "", "| Field | Type |", "|---|---|"]
    for key, value in sample.items():
        lines.append(f"| `{key}` | {describe(value)} |")
    lines.append("")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--data-dir', type=Path, default=DATA_DIR)
    parser.add_argument('--out', type=Path, default=DOC_PATH)
    args = parser.parse_args()

    manifest_path = args.data_dir / 'manifest.json'
    if not manifest_path.exists():
        print(f"No manifest at {manifest_path}. Run the pipeline (or migrate_payload) first.")
        return 1

    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    chamber_key = next(iter(manifest['chambers']))
    chamber = manifest['chambers'][chamber_key]
    resources = chamber['resources']

    def load(rel):
        return json.loads((args.data_dir / rel).read_text(encoding='utf-8'))

    core = load(resources['core']['path'])
    speeches = load(resources['speeches']['path'])
    analytics = load(resources['analytics']['global']['path'])

    lines = [
        "# JSON payload structure",
        "",
        "> Generated by `python -m backend.tools.dump_schema`. Do not edit by hand.",
        "",
        "The payload is split into resources so the frontend can render before the",
        "heavy parts arrive. `manifest.json` indexes everything; each resource is",
        "fetched when a view needs it.",
        "",
        "```",
        "data/",
        "  manifest.json                  index: resources, sizes, digests, periods",
        "  <chamber>/core.json            deputies, clusters, stats  (first paint)",
        "  <chamber>/speeches.json        speech records             (map view only)",
        "  <chamber>/analytics/global.json",
        "  <chamber>/analytics/<year>.json",
        "  <chamber>/analytics/<year>-<month>.json",
        "```",
        "",
        "## manifest.json",
        "",
        "```json",
        json.dumps({
            'version': manifest['version'],
            'generated_at': manifest['generated_at'],
            'chambers': {
                chamber_key: {
                    'label': chamber['label'],
                    'stats': '…',
                    'periods': chamber['periods'],
                    'resources': {
                        'core': resources['core'],
                        'speeches': '…',
                        'analytics': {'global': '…', 'by_year': '…', 'by_month': '…'},
                    },
                }
            },
        }, indent=2, ensure_ascii=False)[:1400],
        "```",
        "",
        "Every resource entry carries `path`, `bytes` and a content `digest`.",
        "",
        "## core.json",
        "",
        f"Top-level keys: {', '.join(f'`{k}`' for k in core)}",
        "",
    ]

    if core.get('deputies'):
        lines += field_table(core['deputies'][0], "core.deputies[]")

    if core.get('stats'):
        lines += field_table(core['stats'], "core.stats")

    lines += [
        "`deputies_by_period` holds the same record shape bucketed by period:",
        "`global`, `by_year['2025']`, `by_month['2025-11']`, plus",
        "`available_periods`.",
        "",
    ]

    if speeches:
        lines += field_table(speeches[0], "speeches[]")
        lines += [
            "Notes:",
            "",
            "- `text` is the speech as delivered, truncated for transport. The full",
            "  report is linked by `url`.",
            "- `cluster` is `-1` for speeches too far from every topic to classify;",
            "  `cluster_conf` is the margin between the best and second-best topic.",
            "- `divergence_pct` is the share of a speaker's interventions outside",
            "  their party's dominant theme. It measures topic choice, not dissent.",
            "",
        ]

    lines += [
        "## analytics/*.json",
        "",
        f"Analyzer sections present at global scope: {', '.join(f'`{k}`' for k in analytics)}",
        "",
        "Period files carry the same shape, minus analyzers that decline to run on a",
        "slice: metrics about change over time (`temporal`) and corpus-level labels",
        "(`topics`) are global-only, and others require a minimum sample size. A",
        "period whose analyzers all declined has no file at all, so the frontend",
        "falls back to the global block.",
        "",
    ]

    for name, block in analytics.items():
        if isinstance(block, dict) and block:
            lines.append(f"- `{name}`: {describe(block)}")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines), encoding='utf-8')
    print(f"Wrote {args.out} ({args.out.stat().st_size} bytes)")
    return 0


if __name__ == '__main__':
    sys.exit(main())
